title: Jekyll Site
email: ahtisam.bashir@apexure.com
description: Basic understanding of jekyll.
baseurl: "" 
url: "https://ahtisambashir6.github.io/jekyll_first_ahtisam_bashir/" 
theme: minima
plugins:
  - jekyll-feed
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
